# Neighborhood Computations

In [ ]:
import numpy as np
import igl
import meshplot
root_folder = os.getcwd()

In [160]:
bunny_v, bunny_f = igl.read_triangle_mesh("data/bunny.off")
sbunny_v, sbunny_f = igl.read_triangle_mesh("data/bunny_small.off")
cube_v, cube_f = igl.read_triangle_mesh("data/cube.obj")
sphere_v, sphere_f = igl.read_triangle_mesh("data/sphere.obj")

In [161]:
meshplot.plot(bunny_v, bunny_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

In [26]:
cube_v.shape[0]

array([[-0.5, -0.5,  0.5],
       [ 0.5, -0.5,  0.5],
       [-0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5],
       [-0.5,  0.5, -0.5],
       [ 0.5,  0.5, -0.5],
       [-0.5, -0.5, -0.5],
       [ 0.5, -0.5, -0.5]])

In [30]:
cube_v.shape[0]

8

In [4]:
meshplot.plot(cube_v, cube_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [5]:
meshplot.plot(sphere_v, sphere_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

## Vertex-to-Face Relations

In [112]:
igl.vertex_triangle_adjacency?

In [167]:
# Given V=sbunny_v and F=sbunny_f, print out the vertex-to-face relations
vf, ni = igl.vertex_triangle_adjacency(sbunny_f, sbunny_v.shape[0])

#Extra information
print('sbunny_f', sbunny_f)
print ('size of sbunny_v', sbunny_v.shape[0])
print ('vf',vf)
print ('ni', ni);
print ('size of ni', ni.shape[0])
print ('size of vf', vf.shape[0])

bunny_f [[2784 2497 2027]
 [1077  225 1060]
 [ 425  450  381]
 ...
 [3086 3203 3162]
 [3086 3162 3151]
 [3086 3151 3085]]
size of bunny_v 3485
vf [ 849  850  912 ... 1500 5112 5264]
ni [    0     5     9 ... 20884 20891 20898]
size of ni 3486
size of vf 20898


In [ ]:
adj_list=[]

for i in range (sbunny_v.shape[0]):
    faces=[]
    for j in range (sbunny_f.shape[0]):
        inner=ni[i]+j
        if inner<vf.shape[0]:
            f=vf[inner]
            if f not in faces:
                faces.append(str(f))
    adj_list.append([str(sbunny_v[i]),faces])

In [166]:
f = open('NeighborhoodRelations.txt', 'w')
f.write(adj_list)
f.write('---------------------------------------------------------------------------\n')

TypeError: sequence item 0: expected str instance, list found

## Vertex-to-Vertex Relations

In [141]:
igl.adjacency_list?

In [144]:
# Given V=sbunny_v and F=sbunny_f print out the vertex-to-vertex relations
connections = igl.adjacency_list(sbunny_f)

In [147]:
adj_list = []
for i in range (sbunny_v.shape[0]):
    adj_list.append([i, connections[i]])

In [148]:
f = open('NeighborhoodRelations.txt', 'w')
f.write(adj_list)
f.write('---------------------------------------------------------------------------\n')

[[0, [1, 2, 4, 6, 7]],
 [1, [0, 2, 3, 7]],
 [2, [0, 1, 3, 4]],
 [3, [1, 2, 4, 5, 7]],
 [4, [0, 2, 3, 5, 6]],
 [5, [3, 4, 6, 7]],
 [6, [0, 4, 5, 7]],
 [7, [0, 1, 3, 5, 6]]]

## Shading

Meshplot requires per vertex normals, so we need to "explode" the mesh

In [ ]:
meshplot.plot(cube_v, cube_f, shading={"flat": False})

In [ ]:
meshplot.plot(sphere_v, sphere_f, shading={"flat": False})

### Flat Shading

### Per-vertex Shading

### Per-corner Shading

## Connected Components

## A simple subdivision scheme